### ISSUE TITLE
"Backup destination must be a writable directory!"

### ISSUE THREAD

**Issue by mailinglists35** [ggilder/backup_icloud_notes#1]
installed like this:
````
brew install ruby
git clone https://github.com/ggilder/backup_icloud_notes
cd backup_icloud_notes
mkdir backups
export PATH="/usr/local/opt/ruby/bin:$PATH"
gem install coderay rchardet method_source git pry #doesn't work without these
````

then I run...
````
$ ./backup_icloud_notes.rb -vv ./backups/
Backup destination must be a writable directory!
````

os: mojave

**Comment by mailinglists35** [comment]
oh nevermind. note the double v. it seems I was doing it wrong, one v is correct, two not!

**Comment by mailinglists35** [comment]
at the end though I got this error:
````
Status:
(new repo, no status to show)

Committing latest backup
Pushing changes
Traceback (most recent call last):
	3: from ./backup_icloud_notes.rb:181:in `<main>'
	2: from /usr/local/lib/ruby/gems/2.7.0/gems/git-1.7.0/lib/git/base.rb:329:in `push'
	1: from /usr/local/lib/ruby/gems/2.7.0/gems/git-1.7.0/lib/git/lib.rb:797:in `push'
/usr/local/lib/ruby/gems/2.7.0/gems/git-1.7.0/lib/git/lib.rb:989:in `command': git '--git-dir=/Users/mojave/backup_icloud_notes/backups/.git' '--work-tree=/Users/mojave/backup_icloud_notes/backups' '-c' 'color.ui=false' push 'origin' 'master'  2>&1:fatal: 'origin' does not appear to be a git repository (Git::GitExecuteError)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


````

**Comment by ggilder** [comment]
Yeah, the utility assumes that you have a git repo already set up and synced with a remote. The git error you got says that there is no "origin" remote set up for the git repo. This could probably be changed to not attempt a push if there's no remote — feel free to make a pull request for that if you're so inclined.

Otherwise, a quick way to fix would be to create a remote for the git repo you're using and make sure you can push to it from your backup folder.
